using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MelonStudio.Models
{
    /// <summary>
    /// Specification for a model partition (GPU or CPU).
    /// Maps to partition_spec in hybrid_config.json.
    /// </summary>
    public class PartitionSpec
    {
        [JsonPropertyName("name")]
        public string Name { get; set; } = "";

        [JsonPropertyName("onnx_path")]
        public string OnnxPath { get; set; } = "";

        [JsonPropertyName("layer_start")]
        public int LayerStart { get; set; }

        [JsonPropertyName("layer_end")]
        public int LayerEnd { get; set; }

        [JsonPropertyName("num_layers")]
        public int NumLayers { get; set; }

        [JsonPropertyName("preferred_ep")]
        public List<string> PreferredEp { get; set; } = new();

        [JsonPropertyName("inputs")]
        public List<string> Inputs { get; set; } = new();

        [JsonPropertyName("outputs")]
        public List<string> Outputs { get; set; } = new();
    }

    /// <summary>
    /// Configuration for hybrid CPU/GPU inference.
    /// Loaded from hybrid_config.json generated by split_model.py.
    /// </summary>
    public class HybridConfig
    {
        [JsonPropertyName("version")]
        public string Version { get; set; } = "2.0";

        [JsonPropertyName("source_model")]
        public string SourceModel { get; set; } = "";

        [JsonPropertyName("split_method")]
        public string SplitMethod { get; set; } = "";

        [JsonPropertyName("total_layers")]
        public int TotalLayers { get; set; }

        [JsonPropertyName("split_layer")]
        public int SplitLayer { get; set; }

        [JsonPropertyName("gpu_partition")]
        public PartitionSpec GpuPartition { get; set; } = new();

        [JsonPropertyName("cpu_partition")]
        public PartitionSpec CpuPartition { get; set; } = new();

        [JsonPropertyName("interface_tensors")]
        public Dictionary<string, string> InterfaceTensors { get; set; } = new();

        // Computed properties for UI
        [JsonIgnore]
        public string Summary => $"{GpuPartition.NumLayers} GPU + {CpuPartition.NumLayers} CPU layers";

        [JsonIgnore]
        public bool IsValid => 
            !string.IsNullOrEmpty(GpuPartition.OnnxPath) && 
            !string.IsNullOrEmpty(CpuPartition.OnnxPath) &&
            TotalLayers > 0 &&
            SplitLayer > 0 && SplitLayer < TotalLayers;
    }
}

