using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MelonStudio.Models
{
    /// <summary>
    /// Specification for a model partition (GPU or CPU).
    /// Maps to partition_spec in hybrid_config.json.
    /// </summary>
    public class PartitionSpec
    {
        [JsonPropertyName("name")]
        public string Name { get; set; } = "";

        [JsonPropertyName("onnx_path")]
        public string OnnxPath { get; set; } = "";

        [JsonPropertyName("layer_start")]
        public int LayerStart { get; set; }

        [JsonPropertyName("layer_end")]
        public int LayerEnd { get; set; }

        [JsonPropertyName("num_layers")]
        public int NumLayers { get; set; }

        [JsonPropertyName("preferred_ep")]
        public List<string> PreferredEp { get; set; } = new();

        [JsonPropertyName("kv_cache_layers")]
        public int KvCacheLayers { get; set; }

        [JsonPropertyName("estimated_size_gb")]
        public double EstimatedSizeGb { get; set; }
    }

    /// <summary>
    /// Interface tensor specification for passing hidden states between partitions.
    /// </summary>
    public class InterfaceTensor
    {
        [JsonPropertyName("name")]
        public string Name { get; set; } = "hidden_states";

        [JsonPropertyName("shape")]
        public List<object> Shape { get; set; } = new(); // ["batch_size", "sequence_length", hidden_size]

        [JsonPropertyName("dtype")]
        public string Dtype { get; set; } = "fp16";
    }

    /// <summary>
    /// KV cache schema for hybrid inference.
    /// </summary>
    public class KvCacheSchema
    {
        [JsonPropertyName("key_shape")]
        public List<object> KeyShape { get; set; } = new();

        [JsonPropertyName("value_shape")]
        public List<object> ValueShape { get; set; } = new();

        [JsonPropertyName("dtype")]
        public string Dtype { get; set; } = "fp16";

        [JsonPropertyName("gpu_layers")]
        public List<int> GpuLayers { get; set; } = new();

        [JsonPropertyName("cpu_layers")]
        public List<int> CpuLayers { get; set; } = new();
    }

    /// <summary>
    /// Configuration for hybrid CPU/GPU inference.
    /// Loaded from hybrid_config.json generated by split_model2.py.
    /// </summary>
    public class HybridConfig
    {
        [JsonPropertyName("version")]
        public string Version { get; set; } = "1.0";

        [JsonPropertyName("source_model")]
        public string SourceModel { get; set; } = "";

        [JsonPropertyName("architecture")]
        public string Architecture { get; set; } = "";

        [JsonPropertyName("total_layers")]
        public int TotalLayers { get; set; }

        [JsonPropertyName("split_layer")]
        public int SplitLayer { get; set; }

        [JsonPropertyName("hidden_size")]
        public int HiddenSize { get; set; }

        [JsonPropertyName("num_attention_heads")]
        public int NumAttentionHeads { get; set; }

        [JsonPropertyName("num_kv_heads")]
        public int NumKvHeads { get; set; }

        [JsonPropertyName("head_dim")]
        public int HeadDim { get; set; }

        [JsonPropertyName("vocab_size")]
        public int VocabSize { get; set; }

        [JsonPropertyName("max_position_embeddings")]
        public int MaxPositionEmbeddings { get; set; }

        [JsonPropertyName("torch_dtype")]
        public string TorchDtype { get; set; } = "fp16";

        [JsonPropertyName("gpu_partition")]
        public PartitionSpec GpuPartition { get; set; } = new();

        [JsonPropertyName("cpu_partition")]
        public PartitionSpec CpuPartition { get; set; } = new();

        [JsonPropertyName("interface_tensor")]
        public InterfaceTensor InterfaceTensor { get; set; } = new();

        [JsonPropertyName("kv_cache_schema")]
        public KvCacheSchema KvCacheSchema { get; set; } = new();

        // Computed properties for UI
        [JsonIgnore]
        public string Summary => $"{GpuPartition.NumLayers} GPU + {CpuPartition.NumLayers} CPU layers";

        [JsonIgnore]
        public double TotalEstimatedSizeGb => GpuPartition.EstimatedSizeGb + CpuPartition.EstimatedSizeGb;

        [JsonIgnore]
        public bool IsValid => 
            !string.IsNullOrEmpty(GpuPartition.OnnxPath) && 
            !string.IsNullOrEmpty(CpuPartition.OnnxPath) &&
            TotalLayers > 0 &&
            SplitLayer > 0 && SplitLayer < TotalLayers;
    }
}
